In [3]:
import numpy as np

In [8]:
def maze_solver(x,y,m,n,maze,solution):
    
    if x == m-1 and y == n-1:
        solution[x][y] = 1
        print(solution)
        print()
        solution[x][y] = 0
        return
    
    if x < 0 or y < 0 or x >= m or y >= n or maze[x][y] == 0 or solution[x][y] == 1:
        return
    
    solution[x][y] = 1
    maze_solver(x,y+1,m,n,maze,solution)
    maze_solver(x+1,y,m,n,maze,solution)
    maze_solver(x-1,y,m,n,maze,solution)
    maze_solver(x,y-1,m,n,maze,solution)
    solution[x][y] = 0
    return

maze = np.array([[1,1,1,1],[1,1,0,1],[1,1,0,1],[1,1,1,1]])
solution = np.array([[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]])
maze_solver(0,0,4,4,maze,solution)

[[1 1 1 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]]

[[1 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 1 1]]

[[1 1 0 0]
 [0 1 0 0]
 [1 1 0 0]
 [1 1 1 1]]

[[1 1 0 0]
 [1 1 0 0]
 [1 1 0 0]
 [0 1 1 1]]

[[1 1 0 0]
 [1 1 0 0]
 [1 0 0 0]
 [1 1 1 1]]

[[1 0 0 0]
 [1 1 0 0]
 [0 1 0 0]
 [0 1 1 1]]

[[1 0 0 0]
 [1 1 0 0]
 [1 1 0 0]
 [1 1 1 1]]

[[1 1 1 1]
 [1 1 0 1]
 [0 0 0 1]
 [0 0 0 1]]

[[1 0 0 0]
 [1 0 0 0]
 [1 1 0 0]
 [0 1 1 1]]

[[1 1 1 1]
 [1 1 0 1]
 [1 1 0 1]
 [0 0 0 1]]

[[1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 1 1 1]]

[[1 1 1 1]
 [1 1 0 1]
 [1 1 0 1]
 [1 1 0 1]]



In [62]:
def NQueens(x,y,solution,n):

    if not(checkPos(x,y,n)) or not(checkQueen(x,y,solution,n)):
        return
    
    if sum(sum(solution)) == n-1:
        solution[x][y] = 1
        print(solution)
        print()
        solution[x][y] = 0
        return

    solution[x][y] = 1
    for i in range(0,n):
        for j in range(0,n):
            NQueens(i,j,solution,n)
    solution[x][y] = 0
    return

def checkPos(x,y,n):
    if x < 0 or y < 0 or x >= n or y >= n:
        return False
    return True

def checkQueen(x,y,solution,n):
    queen_indices = np.where(solution == 1)
    for i in range(len(queen_indices[0])):
        x_queen, y_queen = queen_indices[0][i], queen_indices[1][i]
        if not(checkDiagonal(x,y,x_queen,y_queen,n)) or not(checkHoriVerti(x,y,x_queen,y_queen)):
            return False
    return True

def checkDiagonal(x, y, x_queen, y_queen,n):
    indices = []
    i,j = x_queen, y_queen
    while i < n and j < n:
        indices.append((i,j))
        i += 1
        j += 1
        
    i,j = x_queen, y_queen
    i -= 1
    j -= 1
    while i >= 0 and j >= 0:
        indices.append((i,j))
        i -= 1
        j -= 1
        
    i,j = x_queen, y_queen
    i -= 1
    j += 1
    while i >= 0 and j < n:
        indices.append((i,j))
        i -= 1
        j += 1
    
    i,j = x_queen, y_queen
    i += 1
    j -= 1
    while i < n and j >= 0:
        indices.append((i,j))
        i += 1
        j -= 1
    
    if (x,y) in indices:
        return False
    return True

def checkHoriVerti(x,y,x_queen, y_queen):
    if x == x_queen or y == y_queen:
        return False
    return True

In [65]:

solution = np.zeros((5,5))
NQueens(0,0,solution,5)

[[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]]

[[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]]

[[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]]

[[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]]

[[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]]

[[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]]

[[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]

[[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]

[[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]

[[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]

[[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 

In [34]:
solution

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [63]:
np.where(solution == 1)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64))

In [52]:
not(False)

True

In [4]:
def is_valid_move(row, col, board, n):
    
    i = row-1
    while i>=0:
        if board[i][col] == 1:
            return False
        i -= 1
    
    i = row-1
    j = col-1
    while i>=0 and j>=0:
        if board[i][j] == 1:
            return False
        i -= 1
        j -= 1
    
    i = row-1
    j = col+1
    while i>=0 and j<n:
        if board[i][j] == 1:
            return False
        i -= 1
        j += 1
    
    return True

def NQueens(row, n, board):
    
    if row == n:
        print(board)
        return
    
    for col in range(n):
        if is_valid_move(row, col, board, n):
            board[row][col] = 1
            NQueens(row+1,n,board)
            board[row][col] = 0
    return

In [8]:
n = 6
board = np.zeros((n,n))
NQueens(0,n,board)

[[0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]
[[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0.]]
[[0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0.]]


In [24]:
def is_valid_move(row, col, board, n):
    
    j = col-1
    while j>=0:
        if board[row][j] == 1:
            return False
        j-=1
        
    i = row-1
    j = col-1
    while i>=0 and j>=0:
        if board[i][j] == 1:
            return False
        i-=1
        j-=1
    
    i = row+1
    j = col-1
    while i < n and j>=0:
        if board[i][j] == 1:
            return False
        i+=1
        j-=1

    return True

def NQueensColumnWise(col, board, n):
    
    if col == n:
        print(board)
        print()
        return
    
    for row in range(n):
        if is_valid_move(row, col, board,n):
            board[row][col] = 1
            NQueensColumnWise(col+1, board, n)
            board[row][col] = 0
    return

In [25]:
n = 4
board = np.zeros((n,n))
NQueensColumnWise(0,board,n)

[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]

[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]



In [51]:
def is_valid_move(row, col, board, num):
    
    if board[row][col] != 0:
        return False
    
    j = 0
    while j < 9:
        if board[row][j] == num:
            return False
        j+=1
    
    i = 0
    while i < 9:
        if board[i][col] == num:
            return False
        i+=1
    
    dim1 = row//3
    dim2 = col//3
    for i in range(dim1*3,(dim1+1)*3):
        for j in range(dim2*3,(dim2+1)*3):
            if board[i][j] == num:
                return False
    
    return True

def sudoku_solver(row, board, num):
    
    if row == 9:
        print(board)
        return True
    
    for col in range(9):
        if is_valid_move(row, col, board, num):
            board[row][col] = num
            if num == 9:
                sudoku_solver(row+1,board,1)
            else:
                sudoku_solver(row, board, num+1)
            board[row][col] = 0
    return False

In [52]:
puzzle = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0]
])

# fill in some numbers
puzzle[0, 2] = 1
puzzle[0, 3] = 3
puzzle[0, 5] = 8
puzzle[0, 6] = 5

puzzle[1, 0] = 6
puzzle[1, 1] = 9
puzzle[1, 2] = 8
puzzle[1, 5] = 1

puzzle[2, 0] = 5
puzzle[2, 1] = 7
puzzle[2, 7] = 9
puzzle[2, 8] = 2

puzzle[3, 1] = 4
puzzle[3, 2] = 2
puzzle[3, 4] = 7
puzzle[3, 7] = 3

puzzle[4, 3] = 2
puzzle[4, 4] = 3
puzzle[4, 5] = 9
puzzle[4, 7] = 7

puzzle[5, 1] = 1
puzzle[5, 4] = 8
puzzle[5, 6] = 2
puzzle[5, 7] = 5

puzzle[6, 0] = 2
puzzle[6, 6] = 1
puzzle[6, 7] = 8
puzzle[6, 8] = 5

puzzle[7, 3] = 9
puzzle[7, 6] = 3
puzzle[7, 7] = 7
puzzle[7, 8] = 4

puzzle[8, 2] = 7
puzzle[8, 3] = 4
puzzle[8, 5] = 6
puzzle[8, 6] = 9

In [55]:
sudoku_solver(0,puzzle,1)

In [54]:
puzzle = np.array([
    [0, 3, 0, 0, 0, 2, 0, 0, 0],
    [0, 0, 0, 0, 1, 7, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 5, 0],
    [0, 2, 0, 0, 0, 0, 6, 0, 0],
    [4, 0, 0, 5, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 4, 0, 2, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 6, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 7, 0, 0, 0, 0]
])

In [56]:
puzzle

array([[0, 3, 0, 0, 0, 2, 0, 0, 0],
       [0, 0, 0, 0, 1, 7, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 5, 0],
       [0, 2, 0, 0, 0, 0, 6, 0, 0],
       [4, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 7, 0, 0, 0, 0]])